modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
[[mods]]
modId="challengemod"
version="1.1"
displayName="ChallengeMod"
authors="H_Uploader"
description='''Challenges about wither storms.'''